// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package aystzh_protobuf_student

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Student struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Male                 bool     `protobuf:"varint,1,opt,name=male,proto3" json:"male,omitempty"`
	Scores               []int32  `protobuf:"varint,3,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetMale() bool {
	if m != nil {
		return m.Male
	}
	return false
}

func (m *Student) GetScores() []int32 {
	if m != nil {
		return m.Scores
	}
	return nil
}

func init() {
	proto.RegisterType((*Student)(nil), "aystzh.protobuf.student.Student")
}

func init() {
	proto.RegisterFile("student.proto", fileDescriptor_94a1c1b032ad0c00)
}

var fileDescriptor_94a1c1b032ad0c00 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4f, 0xac, 0x2c, 0x2e, 0xa9,
	0xca, 0x80, 0xf0, 0x92, 0x4a, 0xd3, 0xf4, 0xa0, 0xd2, 0x4a, 0x9e, 0x5c, 0xec, 0xc1, 0x10, 0xa6,
	0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98,
	0x0d, 0x12, 0xcb, 0x4d, 0xcc, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x08, 0x02, 0xb3, 0x85,
	0xc4, 0xb8, 0xd8, 0x8a, 0x93, 0xf3, 0x8b, 0x52, 0x8b, 0x25, 0x98, 0x15, 0x98, 0x35, 0x58, 0x83,
	0xa0, 0xbc, 0x24, 0x36, 0xb0, 0xe1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0xe6, 0xa6,
	0x93, 0x7b, 0x00, 0x00, 0x00,
}
